; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=simplifycfg %s | FileCheck %s

;; Check that chained `&&` style branches (a common pattern in floating point
;; range checks) are still folded into a single block when llvm.pseudoprobe
;; markers are present in the branches. Without this, AArch64 codegen cannot
;; emit `fccmp` for the chained compares because the two branches stay split.
;; The pseudoprobe in the folded block is dropped along with the unreachable
;; block; the probe in the predecessor is preserved.

declare void @llvm.pseudoprobe(i64, i64, i32, i64)

define i32 @chained_cmp(float %v, ptr %out) {
; CHECK-LABEL: @chained_cmp(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[CMP1:%.*]] = fcmp olt float [[V:%.*]], f0x35B28000
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -503749374543619030, i64 1, i32 0, i64 -1)
; CHECK-NEXT:    [[CMP2:%.*]] = fcmp ogt float [[V]], f0xBF800001
; CHECK-NEXT:    [[OR_COND:%.*]] = and i1 [[CMP1]], [[CMP2]]
; CHECK-NEXT:    br i1 [[OR_COND]], label [[IF_THEN:%.*]], label [[COMMON_RET:%.*]]
; CHECK:       common.ret:
; CHECK-NEXT:    [[COMMON_RET_OP:%.*]] = phi i32 [ 1, [[IF_THEN]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    ret i32 [[COMMON_RET_OP]]
; CHECK:       if.then:
; CHECK-NEXT:    store float [[V]], ptr [[OUT:%.*]], align 4
; CHECK-NEXT:    br label [[COMMON_RET]]
;
entry:
  %cmp1 = fcmp olt float %v, 0x3EB6500000000000
  call void @llvm.pseudoprobe(i64 -503749374543619030, i64 1, i32 0, i64 -1)
  br i1 %cmp1, label %land.lhs.true, label %ret_zero

land.lhs.true:
  %cmp2 = fcmp ogt float %v, 0xBFF0000020000000
  call void @llvm.pseudoprobe(i64 -503749374543619030, i64 2, i32 0, i64 -1)
  br i1 %cmp2, label %if.then, label %ret_zero

if.then:
  store float %v, ptr %out, align 4
  ret i32 1

ret_zero:
  ret i32 0
}
