; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=aarch64-- < %s | FileCheck %s

; Test sign-bit test (TST) optimization in LowerSELECT_CC for SSO-like patterns.
; These patterns arise in libc++ SSO code where `icmp slt i8 %flag, 0` tests
; whether a string uses heap storage.

declare void @use(i32)

; Existing working case: sign_extend_inreg with single use produces ldrb + tst.
; This is a regression guard for the existing optimization.
define i32 @cat_a_single_size_check(ptr %p) nounwind {
; CHECK-LABEL: cat_a_single_size_check:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldrb w9, [x0]
; CHECK-NEXT:    mov w8, #42 // =0x2a
; CHECK-NEXT:    tst w9, #0x80
; CHECK-NEXT:    mov w9, #100 // =0x64
; CHECK-NEXT:    csel w0, w9, w8, ne
; CHECK-NEXT:    ret
  %val = load i8, ptr %p
  %sext = sext i8 %val to i32
  %cmp = icmp slt i32 %sext, 0
  %sel = select i1 %cmp, i32 100, i32 42
  ret i32 %sel
}

; Sext load case: sign_extend_inreg folded into sext load should become
; ldrb (zextload) + tst instead of ldrsb (sextload) + cmp.
define i64 @cat_a_single_data_check(ptr %p) nounwind {
; CHECK-LABEL: cat_a_single_data_check:
; CHECK:       // %bb.0:
; CHECK-NEXT:    ldrb w9, [x0]
; CHECK-NEXT:    mov w8, #42 // =0x2a
; CHECK-NEXT:    tst x9, #0x80
; CHECK-NEXT:    mov w9, #100 // =0x64
; CHECK-NEXT:    csel x0, x9, x8, ne
; CHECK-NEXT:    ret
  %val = load i8, ptr %p
  %sext = sext i8 %val to i64
  %cmp = icmp slt i64 %sext, 0
  %sel = select i1 %cmp, i64 100, i64 42
  ret i64 %sel
}

; Multi-use sext_inreg across blocks: sext_inreg feeds both a select_cc and a
; live-out CopyToReg. Both blocks should get tst instead of cmp.
; Entry: sign_extend_inreg has multiple uses (select + live-out) -> needs
;        hasOneUse() removal to fire.
; Notempty: sext arrives as AssertSext(CopyFromReg) -> needs AssertSext support.
define i32 @cat_b_size_then_data(i8 %in, i32 %a) nounwind {
; CHECK-LABEL: cat_b_size_then_data:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov w8, #42 // =0x2a
; CHECK-NEXT:    tst w0, #0x80
; CHECK-NEXT:    csel w8, w1, w8, ne
; CHECK-NEXT:    cbz w8, .LBB2_2
; CHECK-NEXT:  // %bb.1: // %notempty
; CHECK-NEXT:    str x30, [sp, #-32]! // 8-byte Folded Spill
; CHECK-NEXT:    stp x20, x19, [sp, #16] // 16-byte Folded Spill
; CHECK-NEXT:    sxtb w20, w0
; CHECK-NEXT:    mov w19, w1
; CHECK-NEXT:    mov w0, w20
; CHECK-NEXT:    bl use
; CHECK-NEXT:    tst w20, #0x80
; CHECK-NEXT:    mov w8, #100 // =0x64
; CHECK-NEXT:    csel w0, w19, w8, ne
; CHECK-NEXT:    ldp x20, x19, [sp, #16] // 16-byte Folded Reload
; CHECK-NEXT:    ldr x30, [sp], #32 // 8-byte Folded Reload
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB2_2:
; CHECK-NEXT:    mov w0, wzr
; CHECK-NEXT:    ret
entry:
  %sext = sext i8 %in to i32
  %cmp = icmp slt i32 %sext, 0
  %sel = select i1 %cmp, i32 %a, i32 42
  %tobool = icmp eq i32 %sel, 0
  br i1 %tobool, label %exit, label %notempty

notempty:
  call void @use(i32 %sext)
  %cmp2 = icmp slt i32 %sext, 0
  %sel2 = select i1 %cmp2, i32 %a, i32 100
  br label %exit

exit:
  %res = phi i32 [ 0, %entry ], [ %sel2, %notempty ]
  ret i32 %res
}

; Three selects: entry gets tst, notempty should also get tst (not cmp).
; Tests that the AssertSext + multi-use fix handles more than two uses.
define i32 @cat_b_triple_use(i8 %in, i32 %a) nounwind {
; CHECK-LABEL: cat_b_triple_use:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    mov w8, #42 // =0x2a
; CHECK-NEXT:    tst w0, #0x80
; CHECK-NEXT:    csel w8, w1, w8, ne
; CHECK-NEXT:    cbz w8, .LBB3_2
; CHECK-NEXT:  // %bb.1: // %notempty
; CHECK-NEXT:    str x30, [sp, #-32]! // 8-byte Folded Spill
; CHECK-NEXT:    stp x20, x19, [sp, #16] // 16-byte Folded Spill
; CHECK-NEXT:    sxtb w20, w0
; CHECK-NEXT:    mov w19, w1
; CHECK-NEXT:    mov w0, w20
; CHECK-NEXT:    bl use
; CHECK-NEXT:    tst w20, #0x80
; CHECK-NEXT:    mov w8, #100 // =0x64
; CHECK-NEXT:    mov w9, #200 // =0xc8
; CHECK-NEXT:    csel w8, w19, w8, ne
; CHECK-NEXT:    ldp x20, x19, [sp, #16] // 16-byte Folded Reload
; CHECK-NEXT:    csel w0, w8, w9, ne
; CHECK-NEXT:    ldr x30, [sp], #32 // 8-byte Folded Reload
; CHECK-NEXT:    ret
; CHECK-NEXT:  .LBB3_2:
; CHECK-NEXT:    mov w0, wzr
; CHECK-NEXT:    ret
entry:
  %sext = sext i8 %in to i32
  %cmp1 = icmp slt i32 %sext, 0
  %sel1 = select i1 %cmp1, i32 %a, i32 42
  %tobool = icmp eq i32 %sel1, 0
  br i1 %tobool, label %exit, label %notempty

notempty:
  call void @use(i32 %sext)
  %cmp2 = icmp slt i32 %sext, 0
  %sel2 = select i1 %cmp2, i32 %a, i32 100
  %cmp3 = icmp slt i32 %sext, 0
  %sel3 = select i1 %cmp3, i32 %sel2, i32 200
  br label %exit

exit:
  %res = phi i32 [ 0, %entry ], [ %sel3, %notempty ]
  ret i32 %res
}
