; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=instcombine -S | FileCheck %s

declare void @use(i32)

define { i32, i32 } @arm_multiuse_same_side(i1 %c, i32 %a, i32 %b, i32 %x, i32 %y, i32 %z) {
; CHECK-LABEL: @arm_multiuse_same_side(
; CHECK-NEXT:    [[S:%.*]] = select i1 [[C:%.*]], i32 [[A:%.*]], i32 [[B:%.*]]
; CHECK-NEXT:    call void @use(i32 [[S]])
; CHECK-NEXT:    [[V:%.*]] = mul i32 [[A]], [[X:%.*]]
; CHECK-NEXT:    [[R0:%.*]] = select i1 [[C]], i32 [[V]], i32 [[Y:%.*]]
; CHECK-NEXT:    [[R1:%.*]] = select i1 [[C]], i32 [[V]], i32 [[Z:%.*]]
; CHECK-NEXT:    [[I0:%.*]] = insertvalue { i32, i32 } poison, i32 [[R0]], 0
; CHECK-NEXT:    [[I1:%.*]] = insertvalue { i32, i32 } [[I0]], i32 [[R1]], 1
; CHECK-NEXT:    ret { i32, i32 } [[I1]]
;
  %s = select i1 %c, i32 %a, i32 %b
  call void @use(i32 %s)
  %v = mul i32 %s, %x
  %r0 = select i1 %c, i32 %v, i32 %y
  %r1 = select i1 %c, i32 %v, i32 %z
  %i0 = insertvalue { i32, i32 } poison, i32 %r0, 0
  %i1 = insertvalue { i32, i32 } %i0, i32 %r1, 1
  ret { i32, i32 } %i1
}

define { i32, i32 } @counter_pair(i1 %c, i32 %a, i32 %b) {
; CHECK-LABEL: @counter_pair(
; CHECK-NEXT:    [[S:%.*]] = select i1 [[C:%.*]], i32 [[B:%.*]], i32 [[A:%.*]]
; CHECK-NEXT:    [[INC:%.*]] = add i32 [[S]], 1
; CHECK-NEXT:    [[AN:%.*]] = select i1 [[C]], i32 [[A]], i32 [[INC]]
; CHECK-NEXT:    [[BN:%.*]] = select i1 [[C]], i32 [[INC]], i32 [[B]]
; CHECK-NEXT:    [[I0:%.*]] = insertvalue { i32, i32 } poison, i32 [[AN]], 0
; CHECK-NEXT:    [[I1:%.*]] = insertvalue { i32, i32 } [[I0]], i32 [[BN]], 1
; CHECK-NEXT:    ret { i32, i32 } [[I1]]
;
  %s = select i1 %c, i32 %b, i32 %a
  %inc = add i32 %s, 1
  %an = select i1 %c, i32 %a, i32 %inc
  %bn = select i1 %c, i32 %inc, i32 %b
  %i0 = insertvalue { i32, i32 } poison, i32 %an, 0
  %i1 = insertvalue { i32, i32 } %i0, i32 %bn, 1
  ret { i32, i32 } %i1
}

define { i32, i32, i32 } @counter_pair_live_inner(i1 %c, i32 %a, i32 %b) {
; CHECK-LABEL: @counter_pair_live_inner(
; CHECK-NEXT:    [[S:%.*]] = select i1 [[C:%.*]], i32 [[B:%.*]], i32 [[A:%.*]]
; CHECK-NEXT:    [[INC:%.*]] = add nuw i32 [[S]], 1
; CHECK-NEXT:    [[AN:%.*]] = select i1 [[C]], i32 [[A]], i32 [[INC]]
; CHECK-NEXT:    [[BN:%.*]] = select i1 [[C]], i32 [[INC]], i32 [[B]]
; CHECK-NEXT:    [[I0:%.*]] = insertvalue { i32, i32, i32 } poison, i32 [[AN]], 0
; CHECK-NEXT:    [[I1:%.*]] = insertvalue { i32, i32, i32 } [[I0]], i32 [[BN]], 1
; CHECK-NEXT:    [[I2:%.*]] = insertvalue { i32, i32, i32 } [[I1]], i32 [[S]], 2
; CHECK-NEXT:    ret { i32, i32, i32 } [[I2]]
;
  %s = select i1 %c, i32 %b, i32 %a
  %inc = add nuw i32 %s, 1
  %an = select i1 %c, i32 %a, i32 %inc
  %bn = select i1 %c, i32 %inc, i32 %b
  %i0 = insertvalue { i32, i32, i32 } poison, i32 %an, 0
  %i1 = insertvalue { i32, i32, i32 } %i0, i32 %bn, 1
  %i2 = insertvalue { i32, i32, i32 } %i1, i32 %s, 2
  ret { i32, i32, i32 } %i2
}

define { i32, i32 } @not_pair(i1 %c, i32 %a, i32 %b) {
; CHECK-LABEL: @not_pair(
; CHECK-NEXT:    [[S:%.*]] = select i1 [[C:%.*]], i32 [[A:%.*]], i32 [[B:%.*]]
; CHECK-NEXT:    [[N:%.*]] = xor i32 [[S]], -1
; CHECK-NEXT:    [[AN:%.*]] = select i1 [[C]], i32 [[N]], i32 [[A]]
; CHECK-NEXT:    [[BN:%.*]] = select i1 [[C]], i32 [[B]], i32 [[N]]
; CHECK-NEXT:    [[I0:%.*]] = insertvalue { i32, i32 } poison, i32 [[AN]], 0
; CHECK-NEXT:    [[I1:%.*]] = insertvalue { i32, i32 } [[I0]], i32 [[BN]], 1
; CHECK-NEXT:    ret { i32, i32 } [[I1]]
;
  %s = select i1 %c, i32 %a, i32 %b
  %n = xor i32 %s, -1
  %an = select i1 %c, i32 %n, i32 %a
  %bn = select i1 %c, i32 %b, i32 %n
  %i0 = insertvalue { i32, i32 } poison, i32 %an, 0
  %i1 = insertvalue { i32, i32 } %i0, i32 %bn, 1
  ret { i32, i32 } %i1
}

define { <4 x i32>, <4 x i32> } @counter_pair_vec(<4 x i1> %c, <4 x i32> %a, <4 x i32> %b) {
; CHECK-LABEL: @counter_pair_vec(
; CHECK-NEXT:    [[S:%.*]] = select <4 x i1> [[C:%.*]], <4 x i32> [[B:%.*]], <4 x i32> [[A:%.*]]
; CHECK-NEXT:    [[INC:%.*]] = add <4 x i32> [[S]], splat (i32 1)
; CHECK-NEXT:    [[AN:%.*]] = select <4 x i1> [[C]], <4 x i32> [[A]], <4 x i32> [[INC]]
; CHECK-NEXT:    [[BN:%.*]] = select <4 x i1> [[C]], <4 x i32> [[INC]], <4 x i32> [[B]]
; CHECK-NEXT:    [[I0:%.*]] = insertvalue { <4 x i32>, <4 x i32> } poison, <4 x i32> [[AN]], 0
; CHECK-NEXT:    [[I1:%.*]] = insertvalue { <4 x i32>, <4 x i32> } [[I0]], <4 x i32> [[BN]], 1
; CHECK-NEXT:    ret { <4 x i32>, <4 x i32> } [[I1]]
;
  %s = select <4 x i1> %c, <4 x i32> %b, <4 x i32> %a
  %inc = add <4 x i32> %s, splat (i32 1)
  %an = select <4 x i1> %c, <4 x i32> %a, <4 x i32> %inc
  %bn = select <4 x i1> %c, <4 x i32> %inc, <4 x i32> %b
  %i0 = insertvalue { <4 x i32>, <4 x i32> } poison, <4 x i32> %an, 0
  %i1 = insertvalue { <4 x i32>, <4 x i32> } %i0, <4 x i32> %bn, 1
  ret { <4 x i32>, <4 x i32> } %i1
}

; Negative tests

define { i32, i32 } @opposite_sides_variable_operand(i1 %c, i32 %a, i32 %b, i32 %x) {
; CHECK-LABEL: @opposite_sides_variable_operand(
; CHECK-NEXT:    [[S:%.*]] = select i1 [[C:%.*]], i32 [[A:%.*]], i32 [[B:%.*]]
; CHECK-NEXT:    [[V:%.*]] = mul i32 [[S]], [[X:%.*]]
; CHECK-NEXT:    [[AN:%.*]] = select i1 [[C]], i32 [[V]], i32 [[A]]
; CHECK-NEXT:    [[BN:%.*]] = select i1 [[C]], i32 [[B]], i32 [[V]]
; CHECK-NEXT:    [[I0:%.*]] = insertvalue { i32, i32 } poison, i32 [[AN]], 0
; CHECK-NEXT:    [[I1:%.*]] = insertvalue { i32, i32 } [[I0]], i32 [[BN]], 1
; CHECK-NEXT:    ret { i32, i32 } [[I1]]
;
  %s = select i1 %c, i32 %a, i32 %b
  %v = mul i32 %s, %x
  %an = select i1 %c, i32 %v, i32 %a
  %bn = select i1 %c, i32 %b, i32 %v
  %i0 = insertvalue { i32, i32 } poison, i32 %an, 0
  %i1 = insertvalue { i32, i32 } %i0, i32 %bn, 1
  ret { i32, i32 } %i1
}

define i32 @arm_used_outside_select(i1 %c, i32 %a, i32 %b, i32 %x) {
; CHECK-LABEL: @arm_used_outside_select(
; CHECK-NEXT:    [[S:%.*]] = select i1 [[C:%.*]], i32 [[A:%.*]], i32 [[B:%.*]]
; CHECK-NEXT:    call void @use(i32 [[S]])
; CHECK-NEXT:    [[V:%.*]] = mul i32 [[S]], [[X:%.*]]
; CHECK-NEXT:    call void @use(i32 [[V]])
; CHECK-NEXT:    [[R:%.*]] = select i1 [[C]], i32 [[V]], i32 [[B]]
; CHECK-NEXT:    ret i32 [[R]]
;
  %s = select i1 %c, i32 %a, i32 %b
  call void @use(i32 %s)
  %v = mul i32 %s, %x
  call void @use(i32 %v)
  %r = select i1 %c, i32 %v, i32 %b
  ret i32 %r
}

define i32 @arm_used_by_select_on_other_cond(i1 %c, i1 %d, i32 %a, i32 %b, i32 %x) {
; CHECK-LABEL: @arm_used_by_select_on_other_cond(
; CHECK-NEXT:    [[S:%.*]] = select i1 [[C:%.*]], i32 [[A:%.*]], i32 [[B:%.*]]
; CHECK-NEXT:    call void @use(i32 [[S]])
; CHECK-NEXT:    [[V:%.*]] = mul i32 [[S]], [[X:%.*]]
; CHECK-NEXT:    [[TMP1:%.*]] = select i1 [[D:%.*]], i1 true, i1 [[C]]
; CHECK-NEXT:    [[Q:%.*]] = select i1 [[TMP1]], i32 [[V]], i32 [[B]]
; CHECK-NEXT:    ret i32 [[Q]]
;
  %s = select i1 %c, i32 %a, i32 %b
  call void @use(i32 %s)
  %v = mul i32 %s, %x
  %r = select i1 %c, i32 %v, i32 %b
  %q = select i1 %d, i32 %v, i32 %r
  ret i32 %q
}

define i32 @inner_select_on_other_cond(i1 %c, i1 %d, i32 %a, i32 %b, i32 %x) {
; CHECK-LABEL: @inner_select_on_other_cond(
; CHECK-NEXT:    [[S:%.*]] = select i1 [[D:%.*]], i32 [[A:%.*]], i32 [[B:%.*]]
; CHECK-NEXT:    call void @use(i32 [[S]])
; CHECK-NEXT:    [[V:%.*]] = mul i32 [[S]], [[X:%.*]]
; CHECK-NEXT:    [[R:%.*]] = select i1 [[C:%.*]], i32 [[V]], i32 [[B]]
; CHECK-NEXT:    ret i32 [[R]]
;
  %s = select i1 %d, i32 %a, i32 %b
  call void @use(i32 %s)
  %v = mul i32 %s, %x
  %r = select i1 %c, i32 %v, i32 %b
  ret i32 %r
}

define i32 @udiv_not_speculatable(i1 %c, i32 %a, i32 %x) {
; CHECK-LABEL: @udiv_not_speculatable(
; CHECK-NEXT:    [[S:%.*]] = select i1 [[C:%.*]], i32 [[A:%.*]], i32 1
; CHECK-NEXT:    call void @use(i32 [[S]])
; CHECK-NEXT:    [[V:%.*]] = udiv i32 [[X:%.*]], [[S]]
; CHECK-NEXT:    [[R:%.*]] = select i1 [[C]], i32 [[V]], i32 0
; CHECK-NEXT:    ret i32 [[R]]
;
  %s = select i1 %c, i32 %a, i32 1
  call void @use(i32 %s)
  %v = udiv i32 %x, %s
  %r = select i1 %c, i32 %v, i32 0
  ret i32 %r
}

define <4 x i32> @lane_crossing(<4 x i1> %c, <4 x i32> %a, <4 x i32> %b, <4 x i32> %x) {
; CHECK-LABEL: @lane_crossing(
; CHECK-NEXT:    [[S:%.*]] = select <4 x i1> [[C:%.*]], <4 x i32> [[A:%.*]], <4 x i32> [[B:%.*]]
; CHECK-NEXT:    call void @usev(<4 x i32> [[S]])
; CHECK-NEXT:    [[V:%.*]] = shufflevector <4 x i32> [[S]], <4 x i32> poison, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
; CHECK-NEXT:    [[R:%.*]] = select <4 x i1> [[C]], <4 x i32> [[V]], <4 x i32> [[X:%.*]]
; CHECK-NEXT:    ret <4 x i32> [[R]]
;
  %s = select <4 x i1> %c, <4 x i32> %a, <4 x i32> %b
  call void @usev(<4 x i32> %s)
  %v = shufflevector <4 x i32> %s, <4 x i32> poison, <4 x i32> <i32 1, i32 0, i32 3, i32 2>
  %r = select <4 x i1> %c, <4 x i32> %v, <4 x i32> %x
  ret <4 x i32> %r
}

declare void @usev(<4 x i32>)
